defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: warning

development:
  <<: *defaults
  database: sms_verses_dev

test:
  <<: *defaults
  database: sms_verses_test
